services:
  cappu-api:
    build: .
    ports:
      - ${API_PORT}:8080
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - .:/app
    depends_on:
      - cappu-database

  cappu-database:
    image: postgres:14.12
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${POSTGRESQL_EXPOSED_PORT}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data:z