services:
  cappu-api:
    build: .
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - .:/app
    depends_on:
      - cappu-database
    networks:
      - muimi_container_network  

  cappu-database:
    image: postgres:14.12
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - muimi_container_network  

networks:
  muimi_container_network:
    external: true